### ISSUE TITLE
The repository includes secret credentials

### ISSUE THREAD

**Issue by Calinou** [MasterPolska123/pixel-zone-master#1]
Please look at removing secrets in this repository (e.g. `google-services.json` and `*.keystore` file) using [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/). You'll want to generate new API keys and invalidate the previous ones, as you should assume people have kept local copies of this repository :slightly_smiling_face:

**Comment by JezSonic** [comment]
Thanks. I added that files cause I had problems with creating keystore files. google-services.json file will be also removed. I'm glad that someone finally pays attention to such things in this project.  thanks again. #GoogleTranslate
